<?php

namespace App\Services;

use App\Models\Category;
use App\Models\Quote;
use App\Models\Tag;

class QuoteService
{
    /**
     * Sync all relationships for a quote in a single operation.
     *
     * Tags and categories are arrays of {id, name} objects. Existing records have a
     * numeric id; new records (created inline) have id=null and are auto-created via
     * firstOrCreate (slug is generated by the model boot hook).
     *
     * Sources are fully replaced on every call. Passing null or an empty array both
     * result in all existing sources for this quote being deleted. There is no
     * "leave untouched" option — callers must pass the full desired set.
     */
    public function syncRelations(Quote $quote, ?array $tags, ?array $categories, ?array $sources): void
    {
        $quote->tags()->sync(
            collect($tags ?? [])->map(fn ($tag) => isset($tag['id'])
                ? (int) $tag['id']
                : Tag::firstOrCreate(['name' => $tag['name']])->id
            )
        );

        $quote->categories()->sync(
            collect($categories ?? [])->map(fn ($category) => isset($category['id'])
                ? (int) $category['id']
                : Category::firstOrCreate(['name' => $category['name']])->id
            )
        );

        // Sources have no natural key to sync on, so delete then re-insert.
        $quote->sources()->delete();
        foreach ($sources ?? [] as $source) {
            $quote->sources()->create($source);
        }
    }
}
