<?php

namespace App\Services;

use App\Models\Category;
use App\Models\Quote;
use App\Models\Tag;

class QuoteService
{
    /**
     * Sync all relationships for a quote in a single operation.
     *
     * Tags and categories accept either numeric IDs (existing records) or free-text
     * strings (auto-created via firstOrCreate; slug is generated by the model boot hook).
     *
     * Sources are fully replaced on every call. Passing null or an empty array both
     * result in all existing sources for this quote being deleted. There is no
     * "leave untouched" option — callers must pass the full desired set.
     */
    public function syncRelations(Quote $quote, ?array $tags, ?array $categories, ?array $sources): void
    {
        $quote->tags()->sync(
            collect($tags ?? [])->map(fn ($tag) => is_numeric($tag)
                ? (int) $tag
                : Tag::firstOrCreate(['name' => $tag])->id
            )
        );

        $quote->categories()->sync(
            collect($categories ?? [])->map(fn ($category) => is_numeric($category)
                ? (int) $category
                : Category::firstOrCreate(['name' => $category])->id
            )
        );

        // Sources have no natural key to sync on, so delete then re-insert.
        $quote->sources()->delete();
        foreach ($sources ?? [] as $source) {
            $quote->sources()->create($source);
        }
    }
}
