<?php

namespace App\Services;

use App\Models\SavedContext;
use App\Models\Tag;

class SavedContextService
{
    /**
     * Sync tags for a saved context.
     *
     * Tags are arrays of {id, name} objects. Existing records have a numeric id;
     * new records have id=null and are auto-created via firstOrCreate (slug is
     * generated by the Tag model boot hook).
     */
    public function syncTags(SavedContext $savedContext, ?array $tags): void
    {
        $savedContext->tags()->sync(
            collect($tags ?? [])->map(fn ($tag) => isset($tag['id'])
                ? (int) $tag['id']
                : Tag::firstOrCreate(['name' => $tag['name']])->id
            )
        );
    }
}
